package com.ecommerce.inventory.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;

/**
 * INVENTORY ENTITY - Stock Management Model
 * 
 * यह Entity Class database में "inventory" table को represent करती है।
 * 
 * PURPOSE (उद्देश्य):
 * - हर product का stock quantity track करना
 * - Reserved quantity (order के लिए रखा हुआ stock) track करना
 * - Available quantity (बचा हुआ stock) calculate करना
 * 
 * WHY NEEDED (क्यों जरूरी):
 * - बिना inventory tracking के, हम overselling से नहीं बच सकते
 * - Real-time stock check के लिए जरूरी है
 * - Multiple customers एक साथ order करने पर conflict avoid करने के लिए
 * 
 * MICROSERVICE CONCEPT:
 * - यह एक separate service है क्योंकि stock management एक independent concern है
 * - Product Service से अलग है क्योंकि product details ≠ stock management
 * - Separation of Concerns principle follow करता है
 */
@Entity // JPA Annotation: यह class एक database entity है
@Table(name = "inventory") // Database table name = "inventory"
public class Inventory {
    
    /**
     * PRIMARY KEY - Unique identifier for each inventory record
     * Auto-generated by database (1, 2, 3, ...)
     */
    @Id // Primary Key annotation
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment strategy (database auto-generates)
    private Long id;
    
    /**
     * PRODUCT ID - Foreign key to product table
     * यह बताता है कि यह stock किस product का है
     * Example: productId = 1 means iPhone 15 का stock
     */
    private Long productId;
    
    /**
     * QUANTITY - Total stock available in warehouse
     * 
     * @Min(0) Validation: Stock कभी negative नहीं हो सकता
     * 
     * Example: quantity = 100 means warehouse में 100 units हैं
     */
    @Min(0) // Validation: Minimum value is 0 (stock cannot be negative)
    private Integer quantity;
    
    /**
     * RESERVED QUANTITY - Stock जो order के लिए reserve है (अभी payment pending है)
     * 
     * Flow:
     * 1. Customer order देता है → reservedQuantity बढ़ता है
     * 2. Payment success → quantity कम होता है, reservedQuantity कम होता है
     * 3. Payment fail → reservedQuantity कम होता है (stock वापस available हो जाता है)
     * 
     * Example: quantity = 100, reservedQuantity = 10
     * Means: कुल 100 units हैं, लेकिन 10 units order के लिए reserve हैं
     */
    private Integer reservedQuantity = 0; // Default value = 0
    
    /**
     * DEFAULT CONSTRUCTOR
     * JPA/Hibernate के लिए जरूरी है (database से data load करने के लिए)
     */
    public Inventory() {}
    
    // ========== GETTERS AND SETTERS ==========
    // Java Beans Pattern: Private fields को access करने के लिए
    // JPA/Hibernate इन्हें use करता है database operations के लिए
    
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    
    public Long getProductId() { return productId; }
    public void setProductId(Long productId) { this.productId = productId; }
    
    public Integer getQuantity() { return quantity; }
    public void setQuantity(Integer quantity) { this.quantity = quantity; }
    
    public Integer getReservedQuantity() { return reservedQuantity; }
    public void setReservedQuantity(Integer reservedQuantity) { this.reservedQuantity = reservedQuantity; }
    
    /**
     * AVAILABLE QUANTITY - Calculated field (computed value)
     * 
     * Formula: availableQuantity = totalQuantity - reservedQuantity
     * 
     * यह method calculated है (database में store नहीं होता)
     * हर बार call करने पर fresh value calculate होती है
     * 
     * Example:
     * - quantity = 100
     * - reservedQuantity = 10
     * - availableQuantity = 100 - 10 = 90 ✅
     * 
     * WHY CALCULATED:
     * - Always accurate रहता है (no data inconsistency)
     * - Database space save होता है
     * - Real-time value मिलता है
     * 
     * @return Integer - बचा हुआ available stock
     */
    public Integer getAvailableQuantity() {
        return quantity - reservedQuantity; // Total - Reserved = Available
    }
}

